### PR TITLE
Sync recipe with omnia

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
Whoops, didn't mean to mix up these two PRs.

**Comment by jchodera** [comment]
Might as well just update everything here.

**Comment by rmcgibbo** [comment]
what's the goal of appveyor here? it's only going to get triggered when this repo is updated, not pandegroup/openmm

**Comment by jchodera** [comment]
Shoot, good point.

**Comment by jchodera** [comment]
It would be great to discover when merged code breaks on windows, like https://github.com/pandegroup/openmm/pull/1082

**Comment by jchodera** [comment]
I guess that means we want to add appveyor to the https://github.com/pandegroup/openmm proper.

**Comment by rmcgibbo** [comment]
Sounds good. I think we should prune down the matrix, maybe not use miniconda (use the preinstalled python on the build machines) and other stuff to make it as fast as possible. Previously, I think it got really annoying because it took so much longer than travis, and nobody paid attention because it just held up the PRs.

**Comment by jchodera** [comment]
> Sounds good. I think we should prune down the matrix, maybe not use miniconda (use the preinstalled python on the build machines) and other stuff to make it as fast as possible. Previously, I think it got really annoying because it took so much longer than travis, and nobody paid attention because it just held up the PRs.

Agreed.

**Pull request merged**
